spring:
  application:
    name: codeosseum-ares

codeosseum:
  heartbeat:
    checkSeconds: 10
    timeoutSeconds: 120

  eventbus:
    executorThreadCount: 2

  matchmaking:
    schedule:
      initialDelaySeconds: 10
      delaySeconds: 10
